# Generated by Django 4.0.6 on 2022-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='UNIT_PRICE', null=True)),
            ],
            options={
                'db_table': 'SALES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesmen',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='FIRST_NAME', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('place', models.CharField(blank=True, db_column='PLACE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SALESMEN',
                'managed': False,
            },
        ),
    ]
